### ISSUE TITLE
reCaptcha not working

### ISSUE THREAD

**Issue by Alkahna** [mavrosxristoforos/rapid-contact#3]
RapidContact Version: 1.4.23 - 04/02/2020
Joomla Version: 3.9.23

Error in Chrome Developer Tools: reCAPTCHA couldn't find user-provided function: JoomlaInitReCaptcha2

The form shows up fine but somehow the recaptcha is not showing and I get the above error. Any ideas?

**Comment by mavrosxristoforos** [comment]
@Alkahna I apologize for the late response... Somehow, I never got this message. Have you been able to resolve it?

**Comment by MarGraz** [comment]
@mavrosxristoforos same problem here, I'm using **Joomla 3.10.11**, and **Rapid Contact 1.4.27 (free)**, and the standard Joomla plugin "CAPTCHA - Invisible reCAPTCHA", configured with the **invisible recaptcha v3**. 

I receive spam from bots, and **it seems because the form is not compatible with the invisible recaptcha**. 
Did you implement this in the future? 

I'm looking here the [Google docs](https://developers.google.com/recaptcha/docs/v3), and the recaptcha v3 returns a score for each request, on which the contact form module need to take a decision. It's necessary to give to the Joomla admin the possibility to set the threshold level, to accept or not, the request coming from the form.

**Comment by mavrosxristoforos** [comment]
Hi @MarGraz. I was just able to run some thorough tests and Rapid Contact works well with Invisible Recaptcha, both with v2 keys and v3 keys. It is beyond the scope of Rapid Contact to provide options for the threshold level, because those are related with the Invisible ReCaptcha plugin, instead.
